<template>
  <div id="about">
    Nottingham Youth Cricket League 2019
    <p>For help or support contact Simon Park:  simon_park@me.com, 07810891684</p>
  </div>
</template>

<script>
  export default {
    name: 'about'
  }
</script>
<!-- styling for the component -->
<style>
  #about {
    font-family: 'Avenir', Helvetica, Arial, sans-serif;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
    text-align: center;
    color: #2c3e50;
    margin-top: 60px;
  }
</style>
